# Generated by Django 5.2.4 on 2025-08-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password',
            field=models.CharField(default='changeme123', max_length=100),
            preserve_default=False,
        ),
    ]
