# Generated by Django 5.2.4 on 2025-08-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Follow-up', 'Follow-up'), ('Chronic', 'Chronic')], max_length=20)),
            ],
        ),
    ]
