# Generated by Django 5.2.5 on 2025-08-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('checkup_type', models.CharField(choices=[('Follow-up', 'Follow-up'), ('Regular', 'Regular'), ('New', 'New')], max_length=50)),
                ('healthcare_service', models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('Emergency', 'Emergency')], max_length=50)),
                ('bp', models.CharField(max_length=15)),
                ('oxygen_level', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main.patient')),
            ],
        ),
    ]
