# Generated by Django 5.2.5 on 2025-08-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('ip_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('bed_no', models.CharField(blank=True, max_length=20, null=True)),
                ('consultant_name', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('final_diagnosis', models.TextField()),
                ('procedures_done', models.TextField(blank=True, null=True)),
                ('clinical_examination', models.TextField(blank=True, null=True)),
                ('consultations', models.TextField(blank=True, null=True)),
                ('discharge_type', models.CharField(choices=[('Planned', 'Planned'), ('DAMA', 'Discharged Against Medical Advice'), ('DOR', 'Discharged on Request'), ('LAMA', 'Left Against Medical Advice')], default='Planned', max_length=20)),
                ('chief_complaints', models.TextField(blank=True, null=True)),
                ('past_history', models.TextField(blank=True, null=True)),
                ('hospital_course', models.TextField(blank=True, null=True)),
                ('condition_on_discharge', models.TextField(blank=True, null=True)),
                ('discharge_advice', models.TextField(blank=True, null=True)),
                ('diet_advice', models.TextField(blank=True, null=True)),
                ('follow_up', models.TextField(blank=True, null=True)),
                ('emergency_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='main.patient')),
            ],
        ),
    ]
